### ISSUE TITLE
how to process the points that move out when do scale translate or rotation augment op?

### ISSUE THREAD

**Issue by mlinxiang** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#5]
when use imgaug to generate image batch, why no logical to process points that move out image condition?

**Comment by MahmudulAlam** [comment]
Hi @mlinxiang 
This was my headache during implementing augmentation. As a result, I chose the max and min scale, translation, and rotation amount carefully so that the points didn't move out and remained in the image most of the time. For instance, you can try different values and look for the value for which points move out of the image. 

Another way can be checking each point (x, y) whether less than (0, 0) or greater than (128, 128) and if it is true then points moves out of the image and then you can take appropriate action. However, this process seems to slow down the training process. So, I would recommend to chose the augmentation amount carefully.

**Comment by mlinxiang** [comment]
any way to set the outside point to some constant value as no such points?

and why the pos need to multiply 10, i don't find any information about this

**Comment by MahmudulAlam** [comment]
Positions are not actually multiplied by 10 rather used to create ensemble of 10 positions which is a part of our algorithm. In numpy, 
```
np.array([[1,2,3], ] * 3)
```
is actually  
```
array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])
```
Ensembles are created so that after prediction we can take ensemble average which actually reduces the detection error.
