### ISSUE TITLE
OSError: Unable to open file (unable to open file: name = 'yolo.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

### ISSUE THREAD

**Issue by Hanswanglin** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#8]
I use the Mac Os to run the`real-time.py` file, and get the **OSError**, I also search on Google to find others' the same problem. It is probably the `Keras` problem. But I do not how to solve it

**Comment by MahmudulAlam** [comment]
Hi @Hanswanglin 
You have to download the weights file separately from [MEGA](https://mega.nz/#F!6stCxY5b!oB-3279KkhfhRULQFQO7yQ) or [OneDrive](https://www.dropbox.com/sh/7pbfrgaor678eft/AAA8r5ADlMde0WkAtJQO_lo5a?dl=0). Download the weights files and put them in the `weights\` folder in the working directory.
 
Let me know whether the issue is fixed or not.

**Comment by Hanswanglin** [comment]
Thanks @MahmudulAlam 
I have success the `real-time.py` in a Ubuntu server, however, the still failure in MacOS, it seems that is could not recognize the `.h5` files.

Another problem, however, it is the performance, it is a low frame in my Testing.

**Comment by MahmudulAlam** [comment]
@Hanswanglin 
Glad that you succeed. 
Speed performance depends on which GPU you use. I have tested on GTX1050 Ti GPU.

**Comment by Hanswanglin** [comment]
> @Hanswanglin
> Glad that you succeed.
> Speed performance depends on which GPU you use. I have tested on GTX1050 Ti GPU.

I see, so might be it is hard to use the detection on some Embedded hardware for its low performance. Thanks your answer, I will try some other methods.
