### ISSUE TITLE
Datasets

### ISSUE THREAD

**Issue by CVUsers** [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection#9]
Hello， 
I have a question about the dataset from your readme, I can't download the Scut-Ego-Gesture Dataset  ，Because in China, this website has been banned. Can you share it with me in other ways? For example, Google or QQ email: 2665312447@qq.com

**Comment by MahmudulAlam** [comment]
Hi @CVUsers 
They are the owners of the dataset: https://github.com/hyichao/EgoFinger.HCII.SCUT 
Can you please contact them?

**Comment by cavalleria** [comment]
@CVUsers 请问你下载到数据集了吗

**Comment by CVUsers** [comment]
我自己有哈哈哈------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;cavalleria&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月18日(星期一) 下午2:42
收件人:&nbsp;&quot;MahmudulAlam/Unified-Gesture-and-Fingertip-Detection&quot;<Unified-Gesture-and-Fingertip-Detection@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)

**Comment by cavalleria** [comment]
请问你是发邮件申请的吗？我发邮件没动静哈

**Comment by CVUsers** [comment]
这个是什么数据来着，我有了，我自己采集了6w张哈哈哈哈，你可以找我要，我公众号做数据的，DeepAI 视界------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;cavalleria&quot;<notifications@github.com&gt;
发送时间:&nbsp;2021年1月18日(星期一) 下午3:25
收件人:&nbsp;&quot;MahmudulAlam/Unified-Gesture-and-Fingertip-Detection&quot;<Unified-Gesture-and-Fingertip-Detection@noreply.github.com&gt;;
抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)

**Comment by cavalleria** [comment]
ok，加你了

**Comment by jianghanling** [comment]
> 这个是什么数据来着，我有了，我自己采集了6w张哈哈哈哈，你可以找我要，我公众号做数据的，DeepAI 视界------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;&quot;cavalleria&quot;<notifications@github.com&gt; 发送时间:&nbsp;2021年1月18日(星期一) 下午3:25 收件人:&nbsp;&quot;MahmudulAlam/Unified-Gesture-and-Fingertip-Detection&quot;<Unified-Gesture-and-Fingertip-Detection@noreply.github.com&gt;; 抄送:&nbsp;&quot;CVUsers&quot;<2665312447@qq.com&gt;;&quot;Mention&quot;<mention@noreply.github.com&gt;; 主题:&nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)

我也要！！！！做毕设用！！！

**Comment by CVUsers** [comment]
啥数据呀，忘记了，微信 zxx15277368495z



---Original---
From: ***@***.***&gt;
Date: Mon, Mar 14, 2022 16:01 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)




  
这个是什么数据来着，我有了，我自己采集了6w张哈哈哈哈，你可以找我要，我公众号做数据的，DeepAI 视界------------------&nbsp;原始邮件&nbsp;------------------ ***@***.***&gt; 发送时间:&nbsp;2021年1月18日(星期一) 下午3:25 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)
  
我也要！！！！做毕设用！！！
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jianghanling** [comment]
微信联系你啦！！感谢帮忙


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MahmudulAlam/Unified-Gesture-and-Fingertip-Detection"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年3月14日(星期一) 下午4:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9)





 啥数据呀，忘记了，微信 zxx15277368495z 
 
 
 
 ---Original--- 
 From: ***@***.***&amp;gt; 
 Date: Mon, Mar 14, 2022 16:01 PM 
 To: ***@***.***&amp;gt;; 
 Cc: ***@***.******@***.***&amp;gt;; 
 Subject: Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9) 
 
 
 
 
    
 这个是什么数据来着，我有了，我自己采集了6w张哈哈哈哈，你可以找我要，我公众号做数据的，DeepAI 视界------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ ***@***.***&amp;gt; 发送时间:&amp;nbsp;2021年1月18日(星期一) 下午3:25 ***@***.***&amp;gt;; ***@***.******@***.***&amp;gt;; 主题:&amp;nbsp;Re: [MahmudulAlam/Unified-Gesture-and-Fingertip-Detection] Datasets (#9) 
    
 我也要！！！！做毕设用！！！ 
   
 — 
 Reply to this email directly, view it on GitHub, or unsubscribe. 
 Triage notifications on the go with GitHub Mobile for iOS or Android.  
 You are receiving this because you were mentioned.Message ID: ***@***.***&amp;gt; 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jianghanling** [comment]
> ok，加你了

hello 请问你拿到数据集了吗
